input_lvs = [
    {
        'X': (0, 201, 1),
        'name': 'Distance', #number of km between input data and actual distance between chosen cities
        'terms': {
            'short': {'umf': ('trapmf', 0, 0, 1, 2.54), 'lmf': ('trapmf', 0, 0, 0.07, 0.89, 1)},
            'average': {'umf': ('trapmf', 1.42, 3.00, 5.00, 6.03), 'lmf': ('trapmf', 3.5, 3.92, 3.92, 4.42, 0.34)},
            'long': {'umf': ('trapmf', 3.95, 5.45, 7.19, 8.52), 'lmf': ('trapmf', 5.65, 6.18, 6.18, 6.50, 0.33)},
            'huge': {'umf': ('trapmf', 7.42, 9, 10, 10), 'lmf': ('trapmf', 9.11, 9.91, 10, 10, 1)},
        }
    },

    {
        'X': (0, 2001, 1),
        'name': 'Price', #price of the trip
        'terms': {
            'small': {'umf': ('trapmf', 0, 0, 1.05, 1.59), 'lmf': ('trapmf', 0, 0, 0.09, 0.8, 1)},
            'normal': {'umf': ('trapmf', 0.95, 2.00, 4.02, 4.56), 'lmf': ('trapmf', 2.52, 2.95, 2.95, 3.32, 0.34)},
            'high': {'umf': ('trapmf', 3.44, 5.00, 8.10, 9.02), 'lmf': ('trapmf', 5.92, 6.38, 6.38, 6.84, 0.33)},
            'extremely high': {'umf': ('trapmf', 7.37, 8.5, 10, 10), 'lmf': ('trapmf', 9.05, 9.88, 10, 10, 1)},
        }
    },

    {
        'X': (0, 21, 1),
        'name': 'Time', #time required to travel
        'terms': {
            'quick': {'umf': ('trapmf', 0, 0, 0.55, 2.22), 'lmf': ('trapmf', 0, 0, 0.08, 0.85, 1)},
            'sufficient': {'umf': ('trapmf', 0.97, 1.5, 3.00, 4.12), 'lmf': ('trapmf', 1.85, 2.2, 2.2, 2.52, 0.34)},
            'lengthy': {'umf': ('trapmf', 3.38, 4.50, 6.05, 7.67), 'lmf': ('trapmf', 5.83, 6.42, 6.42, 6.94, 0.33)},
            'enormous': {'umf': ('trapmf', 6.91, 8, 10, 10), 'lmf': ('trapmf', 8.85, 9.87, 10, 10, 1)},
        }
    },

    {
        'X': (0, 11, 1),
        'name': 'Space', #number of approximate passanger space
        'terms': {
            'little': {'umf': ('trapmf', 0, 0, 0.52, 1.62), 'lmf': ('trapmf', 0, 0, 0.07, 0.71, 1)},
            'enough': {'umf': ('trapmf', 0.89, 1.50, 2.50, 3.13), 'lmf': ('trapmf', 1.65, 1.98, 1.98, 2.28, 0.34)},
            'much': {'umf': ('trapmf', 1.95, 3.50, 5.00, 6.09), 'lmf': ('trapmf', 3.72, 4.11, 4.11, 4.4, 0.33)},
            'very much': {'umf': ('trapmf', 4, 7, 10, 10), 'lmf': ('trapmf', 8.21, 9.8, 10, 10, 1)},
        }
    }
]

output_lv = {
    'X': (0, 10.1, 0.1),
    'name': 'Comfort level',
    'terms': {
        'awful': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
        'low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
        'questionable': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
        'medium': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
        'satisfactory': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
        'perfect': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
        'excellent': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
    }
}

rule_base = [
    (('short', 'small', 'quick', 'little'), 'perfect'),
    (('short', 'small', 'quick', 'enough'), 'excellent'),
    (('short', 'small', 'quick', 'much'), 'excellent'),
    (('short', 'small', 'quick', 'very much'), 'excellent'),
    (('short', 'small', 'sufficient', 'little'), 'perfect'),
    (('short', 'small', 'sufficient', 'enough'), 'perfect'),
    (('short', 'small', 'sufficient', 'much'), 'excellent'),
    (('short', 'small', 'sufficient', 'very much'), 'excellent'),
    (('short', 'small', 'lengthy', 'little'), 'satisfactory'),
    (('short', 'small', 'lengthy', 'enough'), 'perfect'),
    (('short', 'small', 'lengthy', 'much'), 'perfect'),
    (('short', 'small', 'lengthy', 'very much'), 'excellent'),
    (('short', 'small', 'enormous', 'little'), 'medium'),
    (('short', 'small', 'enormous', 'enough'), 'satisfactory'),
    (('short', 'small', 'enormous', 'much'), 'satisfactory'),
    (('short', 'small', 'enormous', 'very much'), 'perfect'),
    (('short', 'normal', 'quick', 'little'), 'satisfactory'),
    (('short', 'normal', 'quick', 'enough'), 'perfect'),
    (('short', 'normal', 'quick', 'much'), 'perfect'),
    (('short', 'normal', 'quick', 'very much'), 'excellent'),
    (('short', 'normal', 'sufficient', 'little'), 'satisfactory'),
    (('short', 'normal', 'sufficient', 'enough'), 'satisfactory'),
    (('short', 'normal', 'sufficient', 'much'), 'perfect'),
    (('short', 'normal', 'sufficient', 'very much'), 'perfect'),
    (('short', 'normal', 'lengthy', 'little'), 'medium'),
    (('short', 'normal', 'lengthy', 'enough'), 'medium'),
    (('short', 'normal', 'lengthy', 'much'), 'satisfactory'),
    (('short', 'normal', 'lengthy', 'very much'), 'satisfactory'),
    (('short', 'normal', 'enormous', 'little'), 'questionable'),
    (('short', 'normal', 'enormous', 'enough'), 'medium'),
    (('short', 'normal', 'enormous', 'much'), 'medium'),
    (('short', 'normal', 'enormous', 'very much'), 'satisfactory'),
    (('short', 'high', 'quick', 'little'), 'questionable'),
    (('short', 'high', 'quick', 'enough'), 'medium'),
    (('short', 'high', 'quick', 'much'), 'satisfactory'),
    (('short', 'high', 'quick', 'very much'), 'satisfactory'),
    (('short', 'high', 'sufficient', 'little'), 'medium'),
    (('short', 'high', 'sufficient', 'enough'), 'medium'),
    (('short', 'high', 'sufficient', 'much'), 'satisfactory'),
    (('short', 'high', 'sufficient', 'very much'), 'satisfactory'),
    (('short', 'high', 'lengthy', 'little'), 'questionable'),
    (('short', 'high', 'lengthy', 'enough'), 'questionable'),
    (('short', 'high', 'lengthy', 'much'), 'medium'),
    (('short', 'high', 'lengthy', 'very much'), 'medium'),
    (('short', 'high', 'enormous', 'little'), 'awful'),
    (('short', 'high', 'enormous', 'enough'), 'low'),
    (('short', 'high', 'enormous', 'much'), 'low'),
    (('short', 'high', 'enormous', 'very much'), 'questionable'),
    (('short', 'extremely high', 'quick', 'little'), 'questionable'),
    (('short', 'extremely high', 'quick', 'enough'), 'questionable'),
    (('short', 'extremely high', 'quick', 'much'), 'medium'),
    (('short', 'extremely high', 'quick', 'very much'), 'medium'),
    (('short', 'extremely high', 'sufficient', 'little'), 'low'),
    (('short', 'extremely high', 'sufficient', 'enough'), 'questionable'),
    (('short', 'extremely high', 'sufficient', 'much'), 'questionable'),
    (('short', 'extremely high', 'sufficient', 'very much'), 'medium'),
    (('short', 'extremely high', 'lengthy', 'little'), 'low'),
    (('short', 'extremely high', 'lengthy', 'enough'), 'low'),
    (('short', 'extremely high', 'lengthy', 'much'), 'questionable'),
    (('short', 'extremely high', 'lengthy', 'very much'), 'medium'),
    (('short', 'extremely high', 'enormous', 'little'), 'awful'),
    (('short', 'extremely high', 'enormous', 'enough'), 'awful'),
    (('short', 'extremely high', 'enormous', 'much'), 'low'),
    (('short', 'extremely high', 'enormous', 'very much'), 'questionable'),
    (('average', 'small', 'quick', 'little'), 'medium'),
    (('average', 'small', 'quick', 'enough'), 'satisfactory'),
    (('average', 'small', 'quick', 'much'), 'satisfactory'),
    (('average', 'small', 'quick', 'very much'), 'perfect'),
    (('average', 'small', 'sufficient', 'little'), 'medium'),
    (('average', 'small', 'sufficient', 'enough'), 'medium'),
    (('average', 'small', 'sufficient', 'much'), 'medium'),
    (('average', 'small', 'sufficient', 'very much'), 'satisfactory'),
    (('average', 'small', 'lengthy', 'little'), 'questionable'),
    (('average', 'small', 'lengthy', 'enough'), 'medium'),
    (('average', 'small', 'lengthy', 'much'), 'satisfactory'),
    (('average', 'small', 'lengthy', 'very much'), 'satisfactory'),
    (('average', 'small', 'enormous', 'little'), 'low'),
    (('average', 'small', 'enormous', 'enough'), 'questionable'),
    (('average', 'small', 'enormous', 'much'), 'questionable'),
    (('average', 'small', 'enormous', 'very much'), 'medium'),
    (('average', 'normal', 'quick', 'little'), 'satisfactory'),
    (('average', 'normal', 'quick', 'enough'), 'satisfactory'),
    (('average', 'normal', 'quick', 'much'), 'perfect'),
    (('average', 'normal', 'quick', 'very much'), 'perfect'),
    (('average', 'normal', 'sufficient', 'little'), 'questionable'),
    (('average', 'normal', 'sufficient', 'enough'), 'medium'),
    (('average', 'normal', 'sufficient', 'much'), 'medium'),
    (('average', 'normal', 'sufficient', 'very much'), 'satisfactory'),
    (('average', 'normal', 'lengthy', 'little'), 'questionable'),
    (('average', 'normal', 'lengthy', 'enough'), 'medium'),
    (('average', 'normal', 'lengthy', 'much'), 'medium'),
    (('average', 'normal', 'lengthy', 'very much'), 'satisfactory'),
    (('average', 'normal', 'enormous', 'little'), 'questionable'),
    (('average', 'normal', 'enormous', 'enough'), 'questionable'),
    (('average', 'normal', 'enormous', 'much'), 'medium'),
    (('average', 'normal', 'enormous', 'very much'), 'medium'),
    (('average', 'high', 'quick', 'little'), 'questionable'),
    (('average', 'high', 'quick', 'enough'), 'medium'),
    (('average', 'high', 'quick', 'much'), 'medium'),
    (('average', 'high', 'quick', 'very much'), 'satisfactory'),
    (('average', 'high', 'sufficient', 'little'), 'questionable'),
    (('average', 'high', 'sufficient', 'enough'), 'medium'),
    (('average', 'high', 'sufficient', 'much'), 'medium'),
    (('average', 'high', 'sufficient', 'very much'), 'satisfactory'),
    (('average', 'high', 'lengthy', 'little'), 'low'),
    (('average', 'high', 'lengthy', 'enough'), 'questionable'),
    (('average', 'high', 'lengthy', 'much'), 'questionable'),
    (('average', 'high', 'lengthy', 'very much'), 'medium'),
    (('average', 'high', 'enormous', 'little'), 'awful'),
    (('average', 'high', 'enormous', 'enough'), 'low'),
    (('average', 'high', 'enormous', 'much'), 'low'),
    (('average', 'high', 'enormous', 'very much'), 'questionable'),
    (('average', 'extremely high', 'quick', 'little'), 'low'),
    (('average', 'extremely high', 'quick', 'enough'), 'questionable'),
    (('average', 'extremely high', 'quick', 'much'), 'medium'),
    (('average', 'extremely high', 'quick', 'very much'), 'medium'),
    (('average', 'extremely high', 'sufficient', 'little'), 'low'),
    (('average', 'extremely high', 'sufficient', 'enough'), 'low'),
    (('average', 'extremely high', 'sufficient', 'much'), 'questionable'),
    (('average', 'extremely high', 'sufficient', 'very much'), 'questionable'),
    (('average', 'extremely high', 'lengthy', 'little'), 'awful'),
    (('average', 'extremely high', 'lengthy', 'enough'), 'low'),
    (('average', 'extremely high', 'lengthy', 'much'), 'low'),
    (('average', 'extremely high', 'lengthy', 'very much'), 'questionable'),
    (('average', 'extremely high', 'enormous', 'little'), 'awful'),
    (('average', 'extremely high', 'enormous', 'enough'), 'awful'),
    (('average', 'extremely high', 'enormous', 'much'), 'low'),
    (('average', 'extremely high', 'enormous', 'very much'), 'low'),
    (('long', 'small', 'quick', 'little'), 'questionable'),
    (('long', 'small', 'quick', 'enough'), 'medium'),
    (('long', 'small', 'quick', 'much'), 'medium'),
    (('long', 'small', 'quick', 'very much'), 'satisfactory'),
    (('long', 'small', 'sufficient', 'little'), 'questionable'),
    (('long', 'small', 'sufficient', 'enough'), 'medium'),
    (('long', 'small', 'sufficient', 'much'), 'medium'),
    (('long', 'small', 'sufficient', 'very much'), 'satisfactory'),
    (('long', 'small', 'lengthy', 'little'), 'questionable'),
    (('long', 'small', 'lengthy', 'enough'), 'questionable'),
    (('long', 'small', 'lengthy', 'much'), 'medium'),
    (('long', 'small', 'lengthy', 'very much'), 'satisfactory'),
    (('long', 'small', 'enormous', 'little'), 'low'),
    (('long', 'small', 'enormous', 'enough'), 'questionable'),
    (('long', 'small', 'enormous', 'much'), 'medium'),
    (('long', 'small', 'enormous', 'very much'), 'medium'),
    (('long', 'normal', 'quick', 'little'), 'medium'),
    (('long', 'normal', 'quick', 'enough'), 'medium'),
    (('long', 'normal', 'quick', 'much'), 'satisfactory'),
    (('long', 'normal', 'quick', 'very much'), 'satisfactory'),
    (('long', 'normal', 'sufficient', 'little'), 'questionable'),
    (('long', 'normal', 'sufficient', 'enough'), 'questionable'),
    (('long', 'normal', 'sufficient', 'much'), 'medium'),
    (('long', 'normal', 'sufficient', 'very much'), 'satisfactory'),
    (('long', 'normal', 'lengthy', 'little'), 'questionable'),
    (('long', 'normal', 'lengthy', 'enough'), 'questionable'),
    (('long', 'normal', 'lengthy', 'much'), 'medium'),
    (('long', 'normal', 'lengthy', 'very much'), 'medium'),
    (('long', 'normal', 'enormous', 'little'), 'low'),
    (('long', 'normal', 'enormous', 'enough'), 'questionable'),
    (('long', 'normal', 'enormous', 'much'), 'questionable'),
    (('long', 'normal', 'enormous', 'very much'), 'medium'),
    (('long', 'high', 'quick', 'little'), 'questionable'),
    (('long', 'high', 'quick', 'enough'), 'questionable'),
    (('long', 'high', 'quick', 'much'), 'medium'),
    (('long', 'high', 'quick', 'very much'), 'medium'),
    (('long', 'high', 'sufficient', 'little'), 'low'),
    (('long', 'high', 'sufficient', 'enough'), 'questionable'),
    (('long', 'high', 'sufficient', 'much'), 'medium'),
    (('long', 'high', 'sufficient', 'very much'), 'medium'),
    (('long', 'high', 'lengthy', 'little'), 'low'),
    (('long', 'high', 'lengthy', 'enough'), 'questionable'),
    (('long', 'high', 'lengthy', 'much'), 'questionable'),
    (('long', 'high', 'lengthy', 'very much'), 'medium'),
    (('long', 'high', 'enormous', 'little'), 'awful'),
    (('long', 'high', 'enormous', 'enough'), 'awful'),
    (('long', 'high', 'enormous', 'much'), 'low'),
    (('long', 'high', 'enormous', 'very much'), 'low'),
    (('long', 'extremely high', 'quick', 'little'), 'low'),
    (('long', 'extremely high', 'quick', 'enough'), 'questionable'),
    (('long', 'extremely high', 'quick', 'much'), 'questionable'),
    (('long', 'extremely high', 'quick', 'very much'), 'medium'),
    (('long', 'extremely high', 'sufficient', 'little'), 'awful'),
    (('long', 'extremely high', 'sufficient', 'enough'), 'low'),
    (('long', 'extremely high', 'sufficient', 'much'), 'low'),
    (('long', 'extremely high', 'sufficient', 'very much'), 'questionable'),
    (('long', 'extremely high', 'lengthy', 'little'), 'awful'),
    (('long', 'extremely high', 'lengthy', 'enough'), 'awful'),
    (('long', 'extremely high', 'lengthy', 'much'), 'low'),
    (('long', 'extremely high', 'lengthy', 'very much'), 'low'),
    (('long', 'extremely high', 'enormous', 'little'), 'awful'),
    (('long', 'extremely high', 'enormous', 'enough'), 'awful'),
    (('long', 'extremely high', 'enormous', 'much'), 'low'),
    (('long', 'extremely high', 'enormous', 'very much'), 'low'),
    (('huge', 'small', 'quick', 'little'), 'low'),
    (('huge', 'small', 'quick', 'enough'), 'questionable'),
    (('huge', 'small', 'quick', 'much'), 'medium'),
    (('huge', 'small', 'quick', 'very much'), 'satisfactory'),
    (('huge', 'small', 'sufficient', 'little'), 'low'),
    (('huge', 'small', 'sufficient', 'enough'), 'questionable'),
    (('huge', 'small', 'sufficient', 'much'), 'questionable'),
    (('huge', 'small', 'sufficient', 'very much'), 'medium'),
    (('huge', 'small', 'lengthy', 'little'), 'questionable'),
    (('huge', 'small', 'lengthy', 'enough'), 'questionable'),
    (('huge', 'small', 'lengthy', 'much'), 'medium'),
    (('huge', 'small', 'lengthy', 'very much'), 'medium'),
    (('huge', 'small', 'enormous', 'little'), 'low'),
    (('huge', 'small', 'enormous', 'enough'), 'low'),
    (('huge', 'small', 'enormous', 'much'), 'questionable'),
    (('huge', 'small', 'enormous', 'very much'), 'medium'),
    (('huge', 'normal', 'quick', 'little'), 'questionable'),
    (('huge', 'normal', 'quick', 'enough'), 'medium'),
    (('huge', 'normal', 'quick', 'much'), 'medium'),
    (('huge', 'normal', 'quick', 'very much'), 'satisfactory'),
    (('huge', 'normal', 'sufficient', 'little'), 'questionable'),
    (('huge', 'normal', 'sufficient', 'enough'), 'questionable'),
    (('huge', 'normal', 'sufficient', 'much'), 'medium'),
    (('huge', 'normal', 'sufficient', 'very much'), 'medium'),
    (('huge', 'normal', 'lengthy', 'little'), 'questionable'),
    (('huge', 'normal', 'lengthy', 'enough'), 'questionable'),
    (('huge', 'normal', 'lengthy', 'much'), 'medium'),
    (('huge', 'normal', 'lengthy', 'very much'), 'medium'),
    (('huge', 'normal', 'enormous', 'little'), 'low'),
    (('huge', 'normal', 'enormous', 'enough'), 'low'),
    (('huge', 'normal', 'enormous', 'much'), 'questionable'),
    (('huge', 'normal', 'enormous', 'very much'), 'questionable'),
    (('huge', 'high', 'quick', 'little'), 'low'),
    (('huge', 'high', 'quick', 'enough'), 'low'),
    (('huge', 'high', 'quick', 'much'), 'questionable'),
    (('huge', 'high', 'quick', 'very much'), 'questionable'),
    (('huge', 'high', 'sufficient', 'little'), 'low'),
    (('huge', 'high', 'sufficient', 'enough'), 'questionable'),
    (('huge', 'high', 'sufficient', 'much'), 'questionable'),
    (('huge', 'high', 'sufficient', 'very much'), 'medium'),
    (('huge', 'high', 'lengthy', 'little'), 'awful'),
    (('huge', 'high', 'lengthy', 'enough'), 'low'),
    (('huge', 'high', 'lengthy', 'much'), 'low'),
    (('huge', 'high', 'lengthy', 'very much'), 'low'),
    (('huge', 'high', 'enormous', 'little'), 'awful'),
    (('huge', 'high', 'enormous', 'enough'), 'awful'),
    (('huge', 'high', 'enormous', 'much'), 'awful'),
    (('huge', 'high', 'enormous', 'very much'), 'low'),
    (('huge', 'extremely high', 'quick', 'little'), 'low'),
    (('huge', 'extremely high', 'quick', 'enough'), 'low'),
    (('huge', 'extremely high', 'quick', 'much'), 'questionable'),
    (('huge', 'extremely high', 'quick', 'very much'), 'questionable'),
    (('huge', 'extremely high', 'sufficient', 'little'), 'awful'),
    (('huge', 'extremely high', 'sufficient', 'enough'), 'awful'),
    (('huge', 'extremely high', 'sufficient', 'much'), 'low'),
    (('huge', 'extremely high', 'sufficient', 'very much'), 'low'),
    (('huge', 'extremely high', 'lengthy', 'little'), 'awful'),
    (('huge', 'extremely high', 'lengthy', 'enough'), 'awful'),
    (('huge', 'extremely high', 'lengthy', 'much'), 'low'),
    (('huge', 'extremely high', 'lengthy', 'very much'), 'low'),
    (('huge', 'extremely high', 'enormous', 'little'), 'awful'),
    (('huge', 'extremely high', 'enormous', 'enough'), 'awful'),
    (('huge', 'extremely high', 'enormous', 'much'), 'awful'),
    (('huge', 'extremely high', 'enormous', 'very much'), 'low')
]
